"""
TORANA Engine

Abstract Plugin Base Class
==========================

Every analysis plugin must inherit from this class.

Examples
--------
- Urban Heat Island
- Flood Risk
- Walkability
- Solar Potential
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class Plugin(ABC):
    """
    Base class for every TORANA analysis plugin.

    The Engine never performs analysis directly.
    Instead, it loads a Plugin that describes
    the analysis to execute.
    """

    # -------------------------------------------------
    # Identity
    # -------------------------------------------------

    @property
    @abstractmethod
    def id(self) -> str:
        """Unique plugin identifier."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable plugin name."""

    @property
    @abstractmethod
    def version(self) -> str:
        """Plugin version."""

    @property
    @abstractmethod
    def description(self) -> str:
        """Plugin description."""

    # -------------------------------------------------
    # Metadata
    # -------------------------------------------------

    @property
    @abstractmethod
    def metadata(self) -> dict[str, Any]:
        """
        Additional plugin metadata.
        """

    # -------------------------------------------------
    # Configuration
    # -------------------------------------------------

    @property
    @abstractmethod
    def configuration_schema(self) -> dict[str, Any]:
        """
        Configuration schema supported
        by this plugin.
        """

    # -------------------------------------------------
    # Dataset Requirements
    # -------------------------------------------------

    @property
    @abstractmethod
    def required_datasets(self) -> list[str]:
        """
        Required datasets.
        """

    @property
    @abstractmethod
    def optional_datasets(self) -> list[str]:
        """
        Optional datasets.
        """

    # -------------------------------------------------
    # Workflow
    # -------------------------------------------------

    @property
    @abstractmethod
    def workflow(self):
        """
        Workflow definition.
        """

    # -------------------------------------------------
    # Outputs
    # -------------------------------------------------

    @property
    @abstractmethod
    def outputs(self) -> list[str]:
        """
        Outputs generated by this plugin.
        """

    # -------------------------------------------------
    # Validation
    # -------------------------------------------------

    @abstractmethod
    def validate(self) -> bool:
        """
        Validate plugin configuration.

        Returns
        -------
        bool
            True if valid.
        """

    # -------------------------------------------------

    def __repr__(self) -> str:

        return (
            f"{self.__class__.__name__}"
            f"(id='{self.id}', version='{self.version}')"
        )